[package]
name = "safe-io"
version = "0.1.0"
authors = ["majorz"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.1"
anyhow = "1"
md-5 = "0.9"
path-absolutize = "3"
regex = "1"
tempfile = "3"
getrandom = "0.2"
glob = "0.3"
log = "0.4"
env_logger = "0.7"
