[package]
name = "safe-io-lib"
version = "0.1.0"
authors = ["majorz"]
description = "safe-io base library"
license = "Apache-2.0"
edition = "2018"

[dependencies]
anyhow = "1"
md-5 = "0.9"
path-absolutize = "3"
regex = "1"
tempfile = "3"
getrandom = "0.2"
glob = "0.3"
log = "0.4"
